variables:
- group: 'Credentials'
- name: SOLUTION_PATH
  value: src/
- name: MAIN_PROJECT_PATH
  value: src/PipelineRD.Validation
- name: TEST_PROJECT_PATH
  value: src/PipelineRD.Validation.Tests
- name: BUILD_CONFIGURATION
  value: 'Release'

parameters:
  - name: STAGING_TAG
    type: string
    default: ' ' # Empty space because the azure does not let us have a optional parameter for now. The code will handle this value if you deploy with an empty space.
    displayName: 'Tag to publish the package in development. Caution: check if the inserted tag is one (major/minor/patch) version higher than the latest tag in master.'

trigger:
  branches:
    include:
    - release/*  
    - hotfix/*
    - bugfix/*
    - feature/*
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - develop
    - master

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildApplication
  displayName: 'Build Application'
  jobs:
  - job: 'UpdateBuildVersion'
    displayName: 'Update build version' 
    steps:
    # In these steps we do not need to checkout the code
    - checkout: none
    # It will update the pipeline build version based on the reason of the trigger.
    # If it is a tag trigger, it will set the build version as the git tag version.
    - bash: |
        if [[ "$(Build.SourceBranch)" =~ "/feature/" ]] ||
           [[ "$(Build.SourceBranch)" =~ "/bugfix/" ]]; 
        then
          echo "Generate Development Version"

          staging_tag=`echo "${{ parameters.STAGING_TAG }}" | xargs`

          if [[ -z "$staging_tag" ]]
          then
            version=`echo "$BUILD_SOURCEVERSIONMESSAGE" | grep -oP '[\[]staging v?\d+.\d+.\d+[\]]' | grep -oP '\d+.\d+.\d+'`
          else
            version=`echo "$staging_tag" | grep -oP '\d+.\d+.\d+'`
          fi

          if [[ -z "$version" ]];
          then
              echo "Version: $(Build.BuildNumber)"
              echo "##vso[task.setvariable variable=PackingNuget;isOutput=true]false"
          else
              echo "Version: $version-alpha.$(Build.BuildNumber)"
              echo "Force alpha development enabled!"
              echo "##vso[task.setvariable variable=PackingNuget;isOutput=true]true"
              echo "##vso[task.setvariable variable=PackageVersion;isOutput=true]$version-alpha.$(Build.BuildNumber)"
              echo "##vso[build.updatebuildnumber]$version-alpha.$(Build.BuildNumber)"
          fi
        elif [[ "$(Build.SourceBranch)" =~ "/tags/" ]];
        then
          version=`sed 's/v//g' <<< $BUILD_SOURCEBRANCHNAME`
          echo "Generate Release Version"
          echo "Version: $(Build.SourceBranchName)"
          echo "##vso[task.setvariable variable=PackingNuget;isOutput=true]true"
          echo "##vso[task.setvariable variable=PackageVersion;isOutput=true]$version"
          echo "##vso[task.setvariable variable=IsRelease;isOutput=true]true"
          echo "##vso[build.updatebuildnumber]$version"
        fi
      displayName: Update Version Number
      name: UpdateBuildVersionNumberTask
    # Get the previous build status and check if the returned XML from curl request
    # has a string 'succeeded' and if it is not ok, it will stop the execution of current build 
    # It will execute it just when the trigger is a tag.
    # - bash: |
    #     STAGING_URL="$(System. CollectionUri)/$(System.TeamProject)/_apis/build/status/$(System.DefinitionId)?branchName=$(UpdateBuildVersionTask.PreviousPrefix)/$(Build.BuildNumber)&stageName=DeployPackage"
    #     STAGING_RESULT=$`curl --silent $STAGING_URL`
    #     echo "URL: $STAGING_URL" 
    #     echo "RESULT: $STAGING_RESULT"
    #     SUCCEEDED=$`echo $STAGING_RESULT | grep -P 'succeeded' -o | head -n 1`
    #     if [[ "$STAGING_RESULT" =~ "succeeded" ]];
    #     then
    #         echo "$PREVIOUS_PREFIX branch is ok!"
    #     else
    #         echo "$PREVIOUS_PREFIX branch is not ok!"
    #         exit 1
    #     fi
    #   condition: contains(variables['Build.SourceBranch'], '/tags/')
    #   displayName: 'Break if release branch is not passing'
    #   name: BreakIsReleaseNotPassing
    - bash: env
      displayName: Show environment variables
  - job: 'Build'
    displayName: 'Build'
    dependsOn: 'UpdateBuildVersion'
    condition: eq(dependencies.UpdateBuildVersion.result, 'Succeeded')
    variables:
      PackingNuget: $[ dependencies.UpdateBuildVersion.outputs['UpdateBuildVersionNumberTask.PackingNuget'] ]
      PackageVersion: $[ dependencies.UpdateBuildVersion.outputs['UpdateBuildVersionNumberTask.PackageVersion'] ]
      IsRelease: $[ dependencies.UpdateBuildVersion.outputs['UpdateBuildVersionNumberTask.IsRelease'] ]
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore Solution'
      inputs:
        command: 'restore'
        projects: '$(SOLUTION_PATH)/**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: 'build'
        arguments: '$(SOLUTION_PATH) --configuration $(BUILD_CONFIGURATION) --no-restore'
    - task: DotNetCoreCLI@2
      displayName: 'Run Unit Tests'
      inputs:
        command: test
        projects: '$(TEST_PROJECT_PATH)/*.csproj'
        arguments: '--configuration $(BUILD_CONFIGURATION) --no-restore --no-build --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
        publishTestResults: true
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage report'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'
        failIfCoverageEmpty: true
    - task: DotNetCoreCLI@2
      displayName: 'Pack Nuget Package ($(BUILD_CONFIGURATION))'
      inputs:
        command: 'custom'
        projects: '$(MAIN_PROJECT_PATH)/*.csproj'
        custom: 'pack'
        arguments: '-p:Configuration=$(BUILD_CONFIGURATION) -p:PackageVersion=$(PackageVersion) -p:Version=$(PackageVersion) --output $(Build.ArtifactStagingDirectory)/nuget'
    - script: ls $(Build.ArtifactStagingDirectory)/nuget
      condition: eq(variables['PackingNuget'], 'true')
      displayName: 'Display contents of nuget path'
    - script: dotnet nuget push --source https://nuget.pkg.github.com/eduardosbcabral/index.json --api-key $(GITHUT_PUBLISH_PACKAGES_PAT) '$(Build.ArtifactStagingDirectory)/nuget/*.nupkg'
      condition: eq(variables['IsRelease'], 'true')
      displayName: 'Publish Package to Github Registry'
    - task: NuGetCommand@2
      displayName: 'Publish Package to nuget.org'
      condition: eq(variables['PackingNuget'], 'true')
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/nuget/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'nuget_org_publish_packages'